<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="GridViewForm.aspx.cs" Inherits="ASPCS2010JavaScriptVSjQuery.GridViewForm" %>

    <link type="text/css" href="jquery-ui-1.8.21.custom/css/ui-lightness/jquery-ui-1.8.21.custom.css" rel="Stylesheet" />    
    <form id="form1" runat="server">
    <div id="divGridView">
         <asp:GridView ID="GridView1" runat="server" DataKeyNames="ID"   
            AutoGenerateColumns="false" AutoGenerateDeleteButton="false" 
            EnableViewState="false" EmptyDataText="No records found." 
            Width="50%" BorderWidth="1px" CellPadding="4" ForeColor="#333333" GridLines="Both">
                <HeaderStyle BackColor="#507CD1" HorizontalAlign="Left" Font-Bold="True" ForeColor="White" />
                <Columns>
                    <asp:BoundField DataField="ID" HeaderText="ID"/>
                    <asp:TemplateField HeaderText="Edit">
                        <ItemTemplate>
                            <a href="javascript:void(0)" onclick="ShowEditBox(<%# Eval("ID") %>)" title="Edit">Edit</a>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Name">
                        <ItemTemplate>
                            <span id="PName<%# Eval("ID") %>"><%# Eval("Name") %></span>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:BoundField HeaderText="Country" DataField="Country" />

                    <asp:TemplateField HeaderText="Delete">
                        <ItemTemplate>
                            <span onclick="return confirm('Are you sure?')">
                                <a href="javascript:DeleteRecord(<%# Eval("ID") %>)" title="Delete"><font color="red">Delete?</font></a>
                            </span>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
            </asp:GridView>
            <p><asp:label id="lblMessage" runat="server" enableviewstate="false" /></p>
             <asp:HiddenField ID="HiddenFieldMessage" runat="server" Value="" />
            <asp:Literal runat="server" ID="litPaging" EnableViewState="False" />            
    </div>
    </form>        
    
    <script type="text/javascript" src="jquery-ui-1.8.21.custom/js/jquery-1.7.2.min.js"></script>
    <script type="text/javascript" src="jquery-ui-1.8.21.custom/js/jquery-ui-1.8.21.custom.min.js"></script>

    <script language="javascript" type="text/javascript">
        // highlight the row when clicked
        $(document).ready(function () {
            $("#divGridView table tbody tr").mouseover(function () {
                $(this).addClass("highlightRow");
            }).mouseout(function () { $(this).removeClass('highlightRow'); })
        });

        // highlight row by clicking it
        $(document).ready(function () {
            $("#divGridView table tbody tr").click(function () {
                $(this).addClass("select");
            })
        });

        // double click delete rows
        $(document).ready(function () {
            $("#divGridView table tbody tr").dblclick(function () {
                // find the id first
                var v = confirm('Are you sure to delete?');
                if (v) {
                    var ID = $(this).find("td:first").text();
                    // remove the row from server side (the database)
                    DeleteRecord(ID);
                    // remove from the clien side
                    $(this).remove();
                }
            })
        });      
    </script>